apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=  # 여기에 base64로 인코딩된 사용자 이름을 입력하세요.
  password: NjQxMjEx  # 여기에 base64로 인코딩된 비밀번호를 입력하세요.
